<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <SupportedPlatform>windows</SupportedPlatform>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="FluentAssertions"/>
        <ProjectReference Include="..\..\src\WinFsp.Native\WinFsp.Native.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\RamDrive.Core\RamDrive.Core.csproj"/>
        <ProjectReference Include="..\..\src\RamDrive.Diagnostics.MemfsReference\RamDrive.Diagnostics.MemfsReference.csproj"/>
        <ProjectReference Include="..\..\src\RamDrive.Diagnostics.DifferentialChecker\RamDrive.Diagnostics.DifferentialChecker.csproj"/>
    </ItemGroup>

</Project>
